#include <platform/init.h>
#include <platform/configuration_private.h>
#include "stm32f4xx_hal.h"
void init_gpio_clk(GPIO_TypeDef * port) {
  if (port == GPIOA) {
    __HAL_RCC_GPIOA_CLK_ENABLE();
  } else if (port == GPIOB) {
    __HAL_RCC_GPIOB_CLK_ENABLE();
  } else if (port == GPIOC) {
    __HAL_RCC_GPIOC_CLK_ENABLE();
  }
}
void init_valve_gpio(void) {
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  /* GPIO Ports Clock Enable */
  init_gpio_clk(INSP_VALVE_PORT);
  init_gpio_clk(EXP_VALVE_PORT);
  init_gpio_clk(TANK_VALVE_PORT);
  /* Set default output level and configure each pin */
  // inspratory valve
  HAL_GPIO_WritePin(INSP_VALVE_PORT, INSP_VALVE_PIN, GPIO_PIN_RESET);
  GPIO_InitStruct.Pin = INSP_VALVE_PIN;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_LOW;
  HAL_GPIO_Init(INSP_VALVE_PORT, &GPIO_InitStruct);
  // expiratory valve
  HAL_GPIO_WritePin(EXP_VALVE_PORT, EXP_VALVE_PIN, GPIO_PIN_RESET);
  GPIO_InitStruct.Pin = EXP_VALVE_PIN;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_LOW;
  HAL_GPIO_Init(EXP_VALVE_PORT, &GPIO_InitStruct);
  // tank valve
  HAL_GPIO_WritePin(TANK_VALVE_PORT, TANK_VALVE_PIN, GPIO_PIN_RESET);
  GPIO_InitStruct.Pin = TANK_VALVE_PIN;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_LOW;
  HAL_GPIO_Init(TANK_VALVE_PORT, &GPIO_InitStruct);
}
/**
 * Initialize the alarm buzzer.
 * 
 * The alarm buzzer is driven by a Pulse-Width Modulation (PWM)
 * signal generated by a timer peripheral. This timer must be
 * configured to count at the desired frequency and then the 
 * compare and capture channel must be set to match the desired
 * pulse width. 
 * 
 * Note that timer channels on the STM32F4 are mapped directly
 * to alternative functions of GPIO pins. E.g., TIM3.CH2 -> PC7.
 * This requires that the GPIO be configured in an "alternative
 * function" (AF) mode.
 */ 
void init_alarm_buzzer() {
  TIM_ClockConfigTypeDef sClockSourceConfig = {0};
  TIM_MasterConfigTypeDef sMasterConfig = {0};
  TIM_OC_InitTypeDef sConfigOC = {0};
  // STEP 0: ensure clock is enabled for this GPIO port.
  init_gpio_clk(ALARM_BUZZ_PORT);
  // STEP 1: Initialize the timer.
  // -----------------------------
  alarm_timer.Instance = ALARM_BUZZ_TIM;
  alarm_timer.Init.Prescaler = 84 - 1;
  alarm_timer.Init.CounterMode = TIM_COUNTERMODE_UP;
  alarm_timer.Init.Period = 65535;
  alarm_timer.Init.ClockDivision = TIM_CLOCKDIVISION_DIV1;
  alarm_timer.Init.AutoReloadPreload = TIM_AUTORELOAD_PRELOAD_DISABLE;
  if (HAL_TIM_Base_Init(&alarm_timer) != HAL_OK) {
    Error_Handler();
  }
  // STEP 2: Set clock source for timer to internal clock (84MHz)
  // -----------------------------
  sClockSourceConfig.ClockSource = TIM_CLOCKSOURCE_INTERNAL;
  if (HAL_TIM_ConfigClockSource(&alarm_timer, &sClockSourceConfig) != HAL_OK) {
    Error_Handler();
  }
  // STEP 3: Initialize timer in PWM mode.
  // -----------------------------
  if (HAL_TIM_PWM_Init(&alarm_timer) != HAL_OK) {
    Error_Handler();
  }
  // STEP 4: We don't require clock syncrohnization.
  // -----------------------------
  sMasterConfig.MasterOutputTrigger = TIM_TRGO_RESET;
  sMasterConfig.MasterSlaveMode = TIM_MASTERSLAVEMODE_DISABLE;
  if (HAL_TIMEx_MasterConfigSynchronization(&alarm_timer, &sMasterConfig) != HAL_OK) {
    Error_Handler();
  }
  // STEP 5: Initialize channel in PWM mode for timer.
  // -----------------------------
  sConfigOC.OCMode = TIM_OCMODE_PWM1;
  sConfigOC.Pulse = 1000;
  sConfigOC.OCPolarity = TIM_OCPOLARITY_HIGH;
  sConfigOC.OCFastMode = TIM_OCFAST_DISABLE;
  if (HAL_TIM_PWM_ConfigChannel(&alarm_timer, &sConfigOC, TIM_CHANNEL_2) != HAL_OK) {
    Error_Handler();
  }
  // STEP 6: Initialize GPIO pin in alternative function mode for PWM
  // -----------------------------
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  GPIO_InitStruct.Pin = ALARM_BUZZ_PIN;
  GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
  GPIO_InitStruct.Alternate = ALARM_BUZZ_AF2;
  HAL_GPIO_Init(ALARM_BUZZ_PORT, &GPIO_InitStruct);
}
/**
 * Initialize the LED used for the alarm.
 */
void init_alarm_led() {
  GPIO_InitTypeDef GPIO_InitStruct = {0};
  /* GPIO Ports Clock Enable */
  init_gpio_clk(ALARM_LED_PORT);
  HAL_GPIO_WritePin(ALARM_LED_PORT, ALARM_LED_PORT, GPIO_PIN_RESET);
  GPIO_InitStruct.Pin = ALARM_LED_PIN;
  GPIO_InitStruct.Mode = GPIO_MODE_OUTPUT_PP;
  GPIO_InitStruct.Pull = GPIO_NOPULL;
  GPIO_InitStruct.Speed = GPIO_SPEED_LOW;
  HAL_GPIO_Init(ALARM_LED_PORT, &GPIO_InitStruct);
}
void init_alarm() {
  init_alarm_led();
  init_alarm_buzzer();
}

/**
  * @brief ADC1 Initialization Function
  * @param None
  * @retval None
  */
void init_adc1(void)
{
  ADC_ChannelConfTypeDef sConfig = {0};

  /* USER CODE BEGIN ADC1_Init 1 */

  /* USER CODE END ADC1_Init 1 */
  /** Configure the global features of the ADC (Clock, Resolution, Data Alignment and number of conversion)
  */
  potentiometer_1.Instance = ADC1;
  potentiometer_1.Init.ClockPrescaler = ADC_CLOCK_SYNC_PCLK_DIV2;
  potentiometer_1.Init.Resolution = ADC_RESOLUTION_12B;
  potentiometer_1.Init.ScanConvMode = DISABLE;
  potentiometer_1.Init.ContinuousConvMode = DISABLE;
  potentiometer_1.Init.DiscontinuousConvMode = DISABLE;
  potentiometer_1.Init.ExternalTrigConvEdge = ADC_EXTERNALTRIGCONVEDGE_NONE;
  potentiometer_1.Init.ExternalTrigConv = ADC_SOFTWARE_START;
  potentiometer_1.Init.DataAlign = ADC_DATAALIGN_RIGHT;
  potentiometer_1.Init.NbrOfConversion = 1;
  potentiometer_1.Init.DMAContinuousRequests = DISABLE;
  potentiometer_1.Init.EOCSelection = ADC_EOC_SINGLE_CONV;
  if (HAL_ADC_Init(&potentiometer_1) != HAL_OK)
  {
    Error_Handler();
  }
  /** Configure for the selected ADC regular channel its corresponding rank in the sequencer and its sample time.
  */
  sConfig.Channel = ADC_CHANNEL_1;
  sConfig.Rank = 1;
  sConfig.SamplingTime = ADC_SAMPLETIME_3CYCLES;
  if (HAL_ADC_ConfigChannel(&potentiometer_1, &sConfig) != HAL_OK)
  {
    Error_Handler();
  }

}

/**
  * @brief USART2 Initialization Function
  * @param None
  * @retval None
  */
void init_uart(void)
{
  serial1.Instance = USART2;
  serial1.Init.BaudRate = 115200;
  serial1.Init.WordLength = UART_WORDLENGTH_8B;
  serial1.Init.StopBits = UART_STOPBITS_1;
  serial1.Init.Parity = UART_PARITY_NONE;
  serial1.Init.Mode = UART_MODE_TX_RX;
  serial1.Init.HwFlowCtl = UART_HWCONTROL_NONE;
  serial1.Init.OverSampling = UART_OVERSAMPLING_16;
  if (HAL_UART_Init(&serial1) != HAL_OK)
  {
    Error_Handler();
  }

}

/**
  * @brief I2C1 Initialization Function
  * @param None
  * @retval None
  */
void init_i2c(void){
  i2c1_bus.Instance = I2C1;
  i2c1_bus.Init.ClockSpeed = 100000;
  i2c1_bus.Init.DutyCycle = I2C_DUTYCYCLE_2;
  i2c1_bus.Init.OwnAddress1 = 0;
  i2c1_bus.Init.AddressingMode = I2C_ADDRESSINGMODE_7BIT;
  i2c1_bus.Init.DualAddressMode = I2C_DUALADDRESS_DISABLE;
  i2c1_bus.Init.OwnAddress2 = 0;
  i2c1_bus.Init.GeneralCallMode = I2C_GENERALCALL_DISABLE;
  i2c1_bus.Init.NoStretchMode = I2C_NOSTRETCH_DISABLE;
  if (HAL_I2C_Init(&i2c1_bus) != HAL_OK)
  {
    Error_Handler();
  }
}